#!/bin/bash
################################################################################
#                                  deploy                                      #
################################################################################
#                                                                              #
#  DESCRIPTION:  Quick script to consistently and reliably upload releases     #
#                to our website.                                               #
#                                                                              #
#  AUTHOR:       Mark Zieg <mzieg@wasatchphotonics.com>                        #
#                                                                              #
################################################################################

APPNAME="RamanSpectralIdentification"

function verifyExists()
{
    local ARCH="$1"
    LOCAL_NAME="${APPNAME}-x.y.z-${ARCH}.msi"
    LOCAL_PATH="${ARCH}/Debug/$LOCAL_NAME"

    if ! [ -f $LOCAL_PATH ]
    then
        echo "ERROR: can't find $LOCAL_PATH"
        exit 1
    fi
}

function postAndRename()
{
    local ARCH="$1"
    
    LOCAL_NAME="${APPNAME}-x.y.z-${ARCH}.msi"
    LOCAL_PATH="${ARCH}/Debug/$LOCAL_NAME"

    REMOTE_NAME="${APPNAME}-${VERSION}-${ARCH}.msi"
    REMOTE_PATH="www/binaries/oem/sig/$REMOTE_NAME"

    scp $LOCAL_PATH $USERNAME@wasatchphotonics.com:$REMOTE_PATH
}

read -p "Username: " USERNAME
read -p "Version:  " VERSION 

# render documentation (TODO: incorporate VERSION into rendered docs)
# export VERSION
# make doc

# verify version number is tagged
if git tag | egrep -q $VERSION
then
    echo "Git tag found"
else
    echo "Git tag not found: $VERSION"
    exit 1
fi

# verify installers
verifyExists "Setup32"

# upload installers
postAndRename "Setup32"

# upload documentation
# rsync --archive doc/doxygen/html/ ${USERNAME}@wasatchphotonics.com:www/api/Wasatch.NET/
